<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>org.scijava</groupId>
		<artifactId>pom-scijava</artifactId>
		<version>44.0.0</version>
		<relativePath />
	</parent>

	<artifactId>scijava-aggregator</artifactId>
	<version>1.0.1-SNAPSHOT</version>
	<packaging>pom</packaging>

	<name>SciJava</name>
	<description>Core components of the SciJava platform.</description>
	<url>https://github.com/scijava/scijava</url>
	<inceptionYear>2017</inceptionYear>
	<organization>
		<name>SciJava</name>
		<url>https://scijava.org/</url>
	</organization>
	<licenses>
		<license>
			<name>N/A - See individual modules</name>
		</license>
	</licenses>

	<developers>
		<developer>
			<name>N/A - see individual modules</name>
		</developer>
	</developers>
	<contributors>
		<contributor>
			<name>N/A - see individual modules</name>
		</contributor>
	</contributors>

	<mailingLists>
		<mailingList>
			<name>N/A - see individual modules</name>
		</mailingList>
	</mailingLists>

	<modules>
		<!--
		The following modules must be built first, before the others,
		because they are implicit dependencies of the build process:
		- scijava-ops-indexer is used as an annotation processor during compilation
		  of other modules relying on the `@implNote op` declaration mechanism.
		- scijava-taglets is a javadoc taglet processor used at javadoc
		  generation time to handle Ops's custom tags (@container, @mutable, etc.).
		-->
		<module>ops-indexer</module>
		<module>taglets</module>
		<!-- End implicit dependencies -->

		<module>awt</module>
		<module>cli</module>
		<module>code-api</module>
		<module>collections</module>
		<module>command3</module>
		<module>common3</module>
		<module>compat</module>
		<module>concurrent</module>
		<module>context-test</module>
		<module>context</module>
		<module>convert3</module>
		<module>discovery-test</module>
		<module>discovery</module>
		<module>events</module>
		<module>execute</module>
		<module>function</module>
		<module>harvest</module>
		<module>imagej-compat</module>
		<module>index</module>
		<module>io3</module>
		<module>javafx</module>
		<module>meta</module>
		<module>ops-api</module>
		<module>ops-compat</module>
		<module>ops-engine</module>
		<module>ops-ext-parser</module>
		<module>ops-flim</module>
		<module>ops-image</module>
		<module>ops-opencv</module>
		<module>ops-spi</module>
		<module>ops-tutorial</module>
		<module>priority</module>
		<module>progress</module>
		<module>script3</module>
		<module>settings</module>
		<module>spi</module>
		<module>struct</module>
		<module>swing</module>
		<module>testutil</module>
		<module>types</module>
		<module>ui3-test</module>
		<module>ui3</module>
	</modules>

	<scm>
		<connection>scm:git:https://github.com/scijava/scijava</connection>
		<developerConnection>scm:git:git@github.com:scijava/scijava</developerConnection>
		<tag>HEAD</tag>
		<url>https://github.com/scijava/scijava</url>
	</scm>
	<issueManagement>
		<system>N/A - see individual modules</system>
	</issueManagement>
	<ciManagement>
		<system>GitHub Actions</system>
		<url>https://github.com/scijava/scijava/actions</url>
	</ciManagement>

	<properties>
		<license.licenseName>N/A</license.licenseName>
		<license.copyrightOwners>N/A</license.copyrightOwners>

		<!-- NB: Do not install/deploy this aggregator POM. -->
		<maven.deploy.skip>true</maven.deploy.skip>
		<maven.install.skip>true</maven.install.skip>
	</properties>

	<profiles>
		<profile>
			<id>benchmarks</id>
			<modules>
				<module>ops-benchmarks</module>
			</modules>
		</profile>
	</profiles>
</project>
