/*
 * #%L
 * ImageJ2 software for multidimensional image processing and analysis.
 * %%
 * Copyright (C) 2014 - 2023 ImageJ2 developers.
 * %%
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice,
 *    this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDERS OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 * #L%
 */

/*
* This is autogenerated source code -- DO NOT EDIT. Instead, edit the
* corresponding template in templates/ and rerun bin/generate.groovy.
*/

package org.scijava.ops.image.simplify;

import net.imglib2.RandomAccessibleInterval;
import net.imglib2.img.array.ArrayImgs;
import net.imglib2.loops.LoopBuilder;
import net.imglib2.type.logic.BitType;
import net.imglib2.type.numeric.complex.ComplexDoubleType;
import net.imglib2.type.numeric.complex.ComplexFloatType;
import net.imglib2.type.numeric.integer.*;
import net.imglib2.type.numeric.real.DoubleType;
import net.imglib2.type.numeric.real.FloatType;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import org.scijava.ops.image.AbstractOpTest;

public class RAIFocusersTest extends AbstractOpTest {

	/**
	 * @param out the output image
	 * @implNote op names='test.simplify.image.BitType', type='Computer'
	 */
	public static void computeBitType(RandomAccessibleInterval<BitType> out) {
		LoopBuilder.setImages(out).forEachPixel(o -> o.setReal(1.0));
	}

	@Test
	public void testSimplifyBitTypeImage() {
		var out = ArrayImgs.doubles(1, 1);
		out.firstElement().set(0.0);
		ops.op("test.simplify.image.BitType").arity0().output(out).compute();
		double expected = 1.0;
		double actual = out.firstElement().get();
		Assertions.assertEquals(expected, actual);
	}

	/**
	 * @param out the output image
	 * @implNote op names='test.simplify.image.Unsigned2BitType', type='Computer'
	 */
	public static void computeUnsigned2BitType(
		RandomAccessibleInterval<Unsigned2BitType> out)
	{
		LoopBuilder.setImages(out).forEachPixel(o -> o.setReal(1.0));
	}

	@Test
	public void testSimplifyUnsigned2BitTypeImage() {
		var out = ArrayImgs.doubles(1, 1);
		out.firstElement().set(0.0);
		ops.op("test.simplify.image.Unsigned2BitType").arity0().output(out)
			.compute();
		double expected = 1.0;
		double actual = out.firstElement().get();
		Assertions.assertEquals(expected, actual);
	}

	/**
	 * @param out the output image
	 * @implNote op names='test.simplify.image.Unsigned4BitType', type='Computer'
	 */
	public static void computeUnsigned4BitType(
		RandomAccessibleInterval<Unsigned4BitType> out)
	{
		LoopBuilder.setImages(out).forEachPixel(o -> o.setReal(1.0));
	}

	@Test
	public void testSimplifyUnsigned4BitTypeImage() {
		var out = ArrayImgs.doubles(1, 1);
		out.firstElement().set(0.0);
		ops.op("test.simplify.image.Unsigned4BitType").arity0().output(out)
			.compute();
		double expected = 1.0;
		double actual = out.firstElement().get();
		Assertions.assertEquals(expected, actual);
	}

	/**
	 * @param out the output image
	 * @implNote op names='test.simplify.image.UnsignedByteType', type='Computer'
	 */
	public static void computeUnsignedByteType(
		RandomAccessibleInterval<UnsignedByteType> out)
	{
		LoopBuilder.setImages(out).forEachPixel(o -> o.setReal(1.0));
	}

	@Test
	public void testSimplifyUnsignedByteTypeImage() {
		var out = ArrayImgs.doubles(1, 1);
		out.firstElement().set(0.0);
		ops.op("test.simplify.image.UnsignedByteType").arity0().output(out)
			.compute();
		double expected = 1.0;
		double actual = out.firstElement().get();
		Assertions.assertEquals(expected, actual);
	}

	/**
	 * @param out the output image
	 * @implNote op names='test.simplify.image.ByteType', type='Computer'
	 */
	public static void computeByteType(RandomAccessibleInterval<ByteType> out) {
		LoopBuilder.setImages(out).forEachPixel(o -> o.setReal(1.0));
	}

	@Test
	public void testSimplifyByteTypeImage() {
		var out = ArrayImgs.doubles(1, 1);
		out.firstElement().set(0.0);
		ops.op("test.simplify.image.ByteType").arity0().output(out).compute();
		double expected = 1.0;
		double actual = out.firstElement().get();
		Assertions.assertEquals(expected, actual);
	}

	/**
	 * @param out the output image
	 * @implNote op names='test.simplify.image.UnsignedShortType', type='Computer'
	 */
	public static void computeUnsignedShortType(
		RandomAccessibleInterval<UnsignedShortType> out)
	{
		LoopBuilder.setImages(out).forEachPixel(o -> o.setReal(1.0));
	}

	@Test
	public void testSimplifyUnsignedShortTypeImage() {
		var out = ArrayImgs.doubles(1, 1);
		out.firstElement().set(0.0);
		ops.op("test.simplify.image.UnsignedShortType").arity0().output(out)
			.compute();
		double expected = 1.0;
		double actual = out.firstElement().get();
		Assertions.assertEquals(expected, actual);
	}

	/**
	 * @param out the output image
	 * @implNote op names='test.simplify.image.ShortType', type='Computer'
	 */
	public static void computeShortType(RandomAccessibleInterval<ShortType> out) {
		LoopBuilder.setImages(out).forEachPixel(o -> o.setReal(1.0));
	}

	@Test
	public void testSimplifyShortTypeImage() {
		var out = ArrayImgs.doubles(1, 1);
		out.firstElement().set(0.0);
		ops.op("test.simplify.image.ShortType").arity0().output(out).compute();
		double expected = 1.0;
		double actual = out.firstElement().get();
		Assertions.assertEquals(expected, actual);
	}

	/**
	 * @param out the output image
	 * @implNote op names='test.simplify.image.Unsigned12BitType', type='Computer'
	 */
	public static void computeUnsigned12BitType(
		RandomAccessibleInterval<Unsigned12BitType> out)
	{
		LoopBuilder.setImages(out).forEachPixel(o -> o.setReal(1.0));
	}

	@Test
	public void testSimplifyUnsigned12BitTypeImage() {
		var out = ArrayImgs.doubles(1, 1);
		out.firstElement().set(0.0);
		ops.op("test.simplify.image.Unsigned12BitType").arity0().output(out)
			.compute();
		double expected = 1.0;
		double actual = out.firstElement().get();
		Assertions.assertEquals(expected, actual);
	}

	/**
	 * @param out the output image
	 * @implNote op names='test.simplify.image.UnsignedIntType', type='Computer'
	 */
	public static void computeUnsignedIntType(
		RandomAccessibleInterval<UnsignedIntType> out)
	{
		LoopBuilder.setImages(out).forEachPixel(o -> o.setReal(1.0));
	}

	@Test
	public void testSimplifyUnsignedIntTypeImage() {
		var out = ArrayImgs.doubles(1, 1);
		out.firstElement().set(0.0);
		ops.op("test.simplify.image.UnsignedIntType").arity0().output(out)
			.compute();
		double expected = 1.0;
		double actual = out.firstElement().get();
		Assertions.assertEquals(expected, actual);
	}

	/**
	 * @param out the output image
	 * @implNote op names='test.simplify.image.IntType', type='Computer'
	 */
	public static void computeIntType(RandomAccessibleInterval<IntType> out) {
		LoopBuilder.setImages(out).forEachPixel(o -> o.setReal(1.0));
	}

	@Test
	public void testSimplifyIntTypeImage() {
		var out = ArrayImgs.doubles(1, 1);
		out.firstElement().set(0.0);
		ops.op("test.simplify.image.IntType").arity0().output(out).compute();
		double expected = 1.0;
		double actual = out.firstElement().get();
		Assertions.assertEquals(expected, actual);
	}

	/**
	 * @param out the output image
	 * @implNote op names='test.simplify.image.UnsignedLongType', type='Computer'
	 */
	public static void computeUnsignedLongType(
		RandomAccessibleInterval<UnsignedLongType> out)
	{
		LoopBuilder.setImages(out).forEachPixel(o -> o.setReal(1.0));
	}

	@Test
	public void testSimplifyUnsignedLongTypeImage() {
		var out = ArrayImgs.doubles(1, 1);
		out.firstElement().set(0.0);
		ops.op("test.simplify.image.UnsignedLongType").arity0().output(out)
			.compute();
		double expected = 1.0;
		double actual = out.firstElement().get();
		Assertions.assertEquals(expected, actual);
	}

	/**
	 * @param out the output image
	 * @implNote op names='test.simplify.image.LongType', type='Computer'
	 */
	public static void computeLongType(RandomAccessibleInterval<LongType> out) {
		LoopBuilder.setImages(out).forEachPixel(o -> o.setReal(1.0));
	}

	@Test
	public void testSimplifyLongTypeImage() {
		var out = ArrayImgs.doubles(1, 1);
		out.firstElement().set(0.0);
		ops.op("test.simplify.image.LongType").arity0().output(out).compute();
		double expected = 1.0;
		double actual = out.firstElement().get();
		Assertions.assertEquals(expected, actual);
	}

	/**
	 * @param out the output image
	 * @implNote op names='test.simplify.image.Unsigned128BitType',
	 *           type='Computer'
	 */
	public static void computeUnsigned128BitType(
		RandomAccessibleInterval<Unsigned128BitType> out)
	{
		LoopBuilder.setImages(out).forEachPixel(o -> o.setReal(1.0));
	}

	@Test
	public void testSimplifyUnsigned128BitTypeImage() {
		var out = ArrayImgs.doubles(1, 1);
		out.firstElement().set(0.0);
		ops.op("test.simplify.image.Unsigned128BitType").arity0().output(out)
			.compute();
		double expected = 1.0;
		double actual = out.firstElement().get();
		Assertions.assertEquals(expected, actual);
	}

	/**
	 * @param out the output image
	 * @implNote op names='test.simplify.image.FloatType', type='Computer'
	 */
	public static void computeFloatType(RandomAccessibleInterval<FloatType> out) {
		LoopBuilder.setImages(out).forEachPixel(o -> o.setReal(1.0));
	}

	@Test
	public void testSimplifyFloatTypeImage() {
		var out = ArrayImgs.doubles(1, 1);
		out.firstElement().set(0.0);
		ops.op("test.simplify.image.FloatType").arity0().output(out).compute();
		double expected = 1.0;
		double actual = out.firstElement().get();
		Assertions.assertEquals(expected, actual);
	}

	/**
	 * @param out the output image
	 * @implNote op names='test.simplify.image.DoubleType', type='Computer'
	 */
	public static void computeDoubleType(
		RandomAccessibleInterval<DoubleType> out)
	{
		LoopBuilder.setImages(out).forEachPixel(o -> o.setReal(1.0));
	}

	@Test
	public void testSimplifyDoubleTypeImage() {
		var out = ArrayImgs.doubles(1, 1);
		out.firstElement().set(0.0);
		ops.op("test.simplify.image.DoubleType").arity0().output(out).compute();
		double expected = 1.0;
		double actual = out.firstElement().get();
		Assertions.assertEquals(expected, actual);
	}

}
