/*
 * This is autogenerated source code -- DO NOT EDIT. Instead, edit the
 * corresponding template in templates/ and rerun bin/generate.groovy.
 */

package org.scijava.ops.function;

import com.google.common.collect.BiMap;
import com.google.common.collect.ImmutableBiMap;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Consumer;

import org.scijava.ops.OpService;
import org.scijava.ops.types.Nil;
import org.scijava.param.Mutable;
import org.scijava.util.Types;

/**
 * Container class for computer-style functional interfaces at various
 * <a href="https://en.wikipedia.org/wiki/Arity">arities</a>.
 * <p>
 * A computer has functional method {@code compute} with a number of arguments
 * corresponding to the arity, plus an additional argument for the preallocated
 * output to be populated by the computation.
 * </p>
 * <p>
 * Each computer interface implements a corresponding {@link Consumer}-style
 * interface (see {@link Consumers}) with arity+1; the consumer's {@code accept}
 * method simply delegates to {@code compute}. This pattern allows computer ops
 * to be used directly as consumers as needed.
 * </p>
 *
 * @author Curtis Rueden
 * @author Gabriel Selzer
 */
public final class Computers {

	private Computers() {
		// NB: Prevent instantiation of utility class.
	}

	// -- BEGIN TEMP --

	/**
	 * All known computer types and their arities. The entries are sorted by
	 * arity, i.e., the {@code i}-th entry has an arity of {@code i}.
	 */
	public static final BiMap<Class<?>, Integer> ALL_COMPUTERS;

	static {
		final Map<Class<?>, Integer> computers = new HashMap<>();
		computers.put(Arity0.class, 0);
		computers.put(Arity1.class, 1);
		computers.put(Arity2.class, 2);
		computers.put(Arity3.class, 3);
		computers.put(Arity4.class, 4);
		computers.put(Arity5.class, 5);
		computers.put(Arity6.class, 6);
		computers.put(Arity7.class, 7);
		computers.put(Arity8.class, 8);
		computers.put(Arity9.class, 9);
		computers.put(Arity10.class, 10);
		computers.put(Arity11.class, 11);
		computers.put(Arity12.class, 12);
		computers.put(Arity13.class, 13);
		computers.put(Arity14.class, 14);
		computers.put(Arity15.class, 15);
		computers.put(Arity16.class, 16);
		ALL_COMPUTERS = ImmutableBiMap.copyOf(computers);
	}

	/**
	 * @return {@code true} if the given type is a {@link #ALL_COMPUTERS known}
	 *         computer type, {@code false} otherwise. <br>
	 *         Note that only the type itself and not its type hierarchy is
	 *         considered.
	 * @throws NullPointerException If {@code type} is {@code null}.
	 */
	public static boolean isComputer(Type type) {
		return ALL_COMPUTERS.containsKey(Types.raw(type));
	}

	public static <O> Arity0<O> match(final OpService ops, final String opName,
		final Nil<O> outType)
	{
		final Nil<Arity0<O>> specialType =
			new Nil<Arity0<O>>()
		{
			@Override
			public Type getType() {
				return Types.parameterize(Arity0.class, //
					new Type[] { outType.getType() });
			}
		};
		return ops.findOp( //
			opName, //
			specialType, //
			new Nil<?>[] { outType }, //
			outType);
	}

	public static <I, O> Arity1<I, O> match(final OpService ops, final String opName,
		final Nil<I> inType, final Nil<O> outType)
	{
		final Nil<Arity1<I, O>> specialType =
			new Nil<Arity1<I, O>>()
		{
			@Override
			public Type getType() {
				return Types.parameterize(Arity1.class, //
					new Type[] { inType.getType(), outType.getType() });
			}
		};
		return ops.findOp( //
			opName, //
			specialType, //
			new Nil<?>[] { inType, outType }, //
			outType);
	}

	public static <I1, I2, O> Arity2<I1, I2, O> match(final OpService ops, final String opName,
		final Nil<I1> in1Type, final Nil<I2> in2Type, final Nil<O> outType)
	{
		final Nil<Arity2<I1, I2, O>> specialType =
			new Nil<Arity2<I1, I2, O>>()
		{
			@Override
			public Type getType() {
				return Types.parameterize(Arity2.class, //
					new Type[] { in1Type.getType(), in2Type.getType(), outType.getType() });
			}
		};
		return ops.findOp( //
			opName, //
			specialType, //
			new Nil<?>[] { in1Type, in2Type, outType }, //
			outType);
	}

	public static <I1, I2, I3, O> Arity3<I1, I2, I3, O> match(final OpService ops, final String opName,
		final Nil<I1> in1Type, final Nil<I2> in2Type, final Nil<I3> in3Type, final Nil<O> outType)
	{
		final Nil<Arity3<I1, I2, I3, O>> specialType =
			new Nil<Arity3<I1, I2, I3, O>>()
		{
			@Override
			public Type getType() {
				return Types.parameterize(Arity3.class, //
					new Type[] { in1Type.getType(), in2Type.getType(), in3Type.getType(), outType.getType() });
			}
		};
		return ops.findOp( //
			opName, //
			specialType, //
			new Nil<?>[] { in1Type, in2Type, in3Type, outType }, //
			outType);
	}

	public static <I1, I2, I3, I4, O> Arity4<I1, I2, I3, I4, O> match(final OpService ops, final String opName,
		final Nil<I1> in1Type, final Nil<I2> in2Type, final Nil<I3> in3Type, final Nil<I4> in4Type, final Nil<O> outType)
	{
		final Nil<Arity4<I1, I2, I3, I4, O>> specialType =
			new Nil<Arity4<I1, I2, I3, I4, O>>()
		{
			@Override
			public Type getType() {
				return Types.parameterize(Arity4.class, //
					new Type[] { in1Type.getType(), in2Type.getType(), in3Type.getType(), in4Type.getType(), outType.getType() });
			}
		};
		return ops.findOp( //
			opName, //
			specialType, //
			new Nil<?>[] { in1Type, in2Type, in3Type, in4Type, outType }, //
			outType);
	}

	public static <I1, I2, I3, I4, I5, O> Arity5<I1, I2, I3, I4, I5, O> match(final OpService ops, final String opName,
		final Nil<I1> in1Type, final Nil<I2> in2Type, final Nil<I3> in3Type, final Nil<I4> in4Type, final Nil<I5> in5Type, final Nil<O> outType)
	{
		final Nil<Arity5<I1, I2, I3, I4, I5, O>> specialType =
			new Nil<Arity5<I1, I2, I3, I4, I5, O>>()
		{
			@Override
			public Type getType() {
				return Types.parameterize(Arity5.class, //
					new Type[] { in1Type.getType(), in2Type.getType(), in3Type.getType(), in4Type.getType(), in5Type.getType(), outType.getType() });
			}
		};
		return ops.findOp( //
			opName, //
			specialType, //
			new Nil<?>[] { in1Type, in2Type, in3Type, in4Type, in5Type, outType }, //
			outType);
	}

	public static <I1, I2, I3, I4, I5, I6, O> Arity6<I1, I2, I3, I4, I5, I6, O> match(final OpService ops, final String opName,
		final Nil<I1> in1Type, final Nil<I2> in2Type, final Nil<I3> in3Type, final Nil<I4> in4Type, final Nil<I5> in5Type, final Nil<I6> in6Type, final Nil<O> outType)
	{
		final Nil<Arity6<I1, I2, I3, I4, I5, I6, O>> specialType =
			new Nil<Arity6<I1, I2, I3, I4, I5, I6, O>>()
		{
			@Override
			public Type getType() {
				return Types.parameterize(Arity6.class, //
					new Type[] { in1Type.getType(), in2Type.getType(), in3Type.getType(), in4Type.getType(), in5Type.getType(), in6Type.getType(), outType.getType() });
			}
		};
		return ops.findOp( //
			opName, //
			specialType, //
			new Nil<?>[] { in1Type, in2Type, in3Type, in4Type, in5Type, in6Type, outType }, //
			outType);
	}

	public static <I1, I2, I3, I4, I5, I6, I7, O> Arity7<I1, I2, I3, I4, I5, I6, I7, O> match(final OpService ops, final String opName,
		final Nil<I1> in1Type, final Nil<I2> in2Type, final Nil<I3> in3Type, final Nil<I4> in4Type, final Nil<I5> in5Type, final Nil<I6> in6Type, final Nil<I7> in7Type, final Nil<O> outType)
	{
		final Nil<Arity7<I1, I2, I3, I4, I5, I6, I7, O>> specialType =
			new Nil<Arity7<I1, I2, I3, I4, I5, I6, I7, O>>()
		{
			@Override
			public Type getType() {
				return Types.parameterize(Arity7.class, //
					new Type[] { in1Type.getType(), in2Type.getType(), in3Type.getType(), in4Type.getType(), in5Type.getType(), in6Type.getType(), in7Type.getType(), outType.getType() });
			}
		};
		return ops.findOp( //
			opName, //
			specialType, //
			new Nil<?>[] { in1Type, in2Type, in3Type, in4Type, in5Type, in6Type, in7Type, outType }, //
			outType);
	}

	public static <I1, I2, I3, I4, I5, I6, I7, I8, O> Arity8<I1, I2, I3, I4, I5, I6, I7, I8, O> match(final OpService ops, final String opName,
		final Nil<I1> in1Type, final Nil<I2> in2Type, final Nil<I3> in3Type, final Nil<I4> in4Type, final Nil<I5> in5Type, final Nil<I6> in6Type, final Nil<I7> in7Type, final Nil<I8> in8Type, final Nil<O> outType)
	{
		final Nil<Arity8<I1, I2, I3, I4, I5, I6, I7, I8, O>> specialType =
			new Nil<Arity8<I1, I2, I3, I4, I5, I6, I7, I8, O>>()
		{
			@Override
			public Type getType() {
				return Types.parameterize(Arity8.class, //
					new Type[] { in1Type.getType(), in2Type.getType(), in3Type.getType(), in4Type.getType(), in5Type.getType(), in6Type.getType(), in7Type.getType(), in8Type.getType(), outType.getType() });
			}
		};
		return ops.findOp( //
			opName, //
			specialType, //
			new Nil<?>[] { in1Type, in2Type, in3Type, in4Type, in5Type, in6Type, in7Type, in8Type, outType }, //
			outType);
	}

	public static <I1, I2, I3, I4, I5, I6, I7, I8, I9, O> Arity9<I1, I2, I3, I4, I5, I6, I7, I8, I9, O> match(final OpService ops, final String opName,
		final Nil<I1> in1Type, final Nil<I2> in2Type, final Nil<I3> in3Type, final Nil<I4> in4Type, final Nil<I5> in5Type, final Nil<I6> in6Type, final Nil<I7> in7Type, final Nil<I8> in8Type, final Nil<I9> in9Type, final Nil<O> outType)
	{
		final Nil<Arity9<I1, I2, I3, I4, I5, I6, I7, I8, I9, O>> specialType =
			new Nil<Arity9<I1, I2, I3, I4, I5, I6, I7, I8, I9, O>>()
		{
			@Override
			public Type getType() {
				return Types.parameterize(Arity9.class, //
					new Type[] { in1Type.getType(), in2Type.getType(), in3Type.getType(), in4Type.getType(), in5Type.getType(), in6Type.getType(), in7Type.getType(), in8Type.getType(), in9Type.getType(), outType.getType() });
			}
		};
		return ops.findOp( //
			opName, //
			specialType, //
			new Nil<?>[] { in1Type, in2Type, in3Type, in4Type, in5Type, in6Type, in7Type, in8Type, in9Type, outType }, //
			outType);
	}

	public static <I1, I2, I3, I4, I5, I6, I7, I8, I9, I10, O> Arity10<I1, I2, I3, I4, I5, I6, I7, I8, I9, I10, O> match(final OpService ops, final String opName,
		final Nil<I1> in1Type, final Nil<I2> in2Type, final Nil<I3> in3Type, final Nil<I4> in4Type, final Nil<I5> in5Type, final Nil<I6> in6Type, final Nil<I7> in7Type, final Nil<I8> in8Type, final Nil<I9> in9Type, final Nil<I10> in10Type, final Nil<O> outType)
	{
		final Nil<Arity10<I1, I2, I3, I4, I5, I6, I7, I8, I9, I10, O>> specialType =
			new Nil<Arity10<I1, I2, I3, I4, I5, I6, I7, I8, I9, I10, O>>()
		{
			@Override
			public Type getType() {
				return Types.parameterize(Arity10.class, //
					new Type[] { in1Type.getType(), in2Type.getType(), in3Type.getType(), in4Type.getType(), in5Type.getType(), in6Type.getType(), in7Type.getType(), in8Type.getType(), in9Type.getType(), in10Type.getType(), outType.getType() });
			}
		};
		return ops.findOp( //
			opName, //
			specialType, //
			new Nil<?>[] { in1Type, in2Type, in3Type, in4Type, in5Type, in6Type, in7Type, in8Type, in9Type, in10Type, outType }, //
			outType);
	}

	public static <I1, I2, I3, I4, I5, I6, I7, I8, I9, I10, I11, O> Arity11<I1, I2, I3, I4, I5, I6, I7, I8, I9, I10, I11, O> match(final OpService ops, final String opName,
		final Nil<I1> in1Type, final Nil<I2> in2Type, final Nil<I3> in3Type, final Nil<I4> in4Type, final Nil<I5> in5Type, final Nil<I6> in6Type, final Nil<I7> in7Type, final Nil<I8> in8Type, final Nil<I9> in9Type, final Nil<I10> in10Type, final Nil<I11> in11Type, final Nil<O> outType)
	{
		final Nil<Arity11<I1, I2, I3, I4, I5, I6, I7, I8, I9, I10, I11, O>> specialType =
			new Nil<Arity11<I1, I2, I3, I4, I5, I6, I7, I8, I9, I10, I11, O>>()
		{
			@Override
			public Type getType() {
				return Types.parameterize(Arity11.class, //
					new Type[] { in1Type.getType(), in2Type.getType(), in3Type.getType(), in4Type.getType(), in5Type.getType(), in6Type.getType(), in7Type.getType(), in8Type.getType(), in9Type.getType(), in10Type.getType(), in11Type.getType(), outType.getType() });
			}
		};
		return ops.findOp( //
			opName, //
			specialType, //
			new Nil<?>[] { in1Type, in2Type, in3Type, in4Type, in5Type, in6Type, in7Type, in8Type, in9Type, in10Type, in11Type, outType }, //
			outType);
	}

	public static <I1, I2, I3, I4, I5, I6, I7, I8, I9, I10, I11, I12, O> Arity12<I1, I2, I3, I4, I5, I6, I7, I8, I9, I10, I11, I12, O> match(final OpService ops, final String opName,
		final Nil<I1> in1Type, final Nil<I2> in2Type, final Nil<I3> in3Type, final Nil<I4> in4Type, final Nil<I5> in5Type, final Nil<I6> in6Type, final Nil<I7> in7Type, final Nil<I8> in8Type, final Nil<I9> in9Type, final Nil<I10> in10Type, final Nil<I11> in11Type, final Nil<I12> in12Type, final Nil<O> outType)
	{
		final Nil<Arity12<I1, I2, I3, I4, I5, I6, I7, I8, I9, I10, I11, I12, O>> specialType =
			new Nil<Arity12<I1, I2, I3, I4, I5, I6, I7, I8, I9, I10, I11, I12, O>>()
		{
			@Override
			public Type getType() {
				return Types.parameterize(Arity12.class, //
					new Type[] { in1Type.getType(), in2Type.getType(), in3Type.getType(), in4Type.getType(), in5Type.getType(), in6Type.getType(), in7Type.getType(), in8Type.getType(), in9Type.getType(), in10Type.getType(), in11Type.getType(), in12Type.getType(), outType.getType() });
			}
		};
		return ops.findOp( //
			opName, //
			specialType, //
			new Nil<?>[] { in1Type, in2Type, in3Type, in4Type, in5Type, in6Type, in7Type, in8Type, in9Type, in10Type, in11Type, in12Type, outType }, //
			outType);
	}

	public static <I1, I2, I3, I4, I5, I6, I7, I8, I9, I10, I11, I12, I13, O> Arity13<I1, I2, I3, I4, I5, I6, I7, I8, I9, I10, I11, I12, I13, O> match(final OpService ops, final String opName,
		final Nil<I1> in1Type, final Nil<I2> in2Type, final Nil<I3> in3Type, final Nil<I4> in4Type, final Nil<I5> in5Type, final Nil<I6> in6Type, final Nil<I7> in7Type, final Nil<I8> in8Type, final Nil<I9> in9Type, final Nil<I10> in10Type, final Nil<I11> in11Type, final Nil<I12> in12Type, final Nil<I13> in13Type, final Nil<O> outType)
	{
		final Nil<Arity13<I1, I2, I3, I4, I5, I6, I7, I8, I9, I10, I11, I12, I13, O>> specialType =
			new Nil<Arity13<I1, I2, I3, I4, I5, I6, I7, I8, I9, I10, I11, I12, I13, O>>()
		{
			@Override
			public Type getType() {
				return Types.parameterize(Arity13.class, //
					new Type[] { in1Type.getType(), in2Type.getType(), in3Type.getType(), in4Type.getType(), in5Type.getType(), in6Type.getType(), in7Type.getType(), in8Type.getType(), in9Type.getType(), in10Type.getType(), in11Type.getType(), in12Type.getType(), in13Type.getType(), outType.getType() });
			}
		};
		return ops.findOp( //
			opName, //
			specialType, //
			new Nil<?>[] { in1Type, in2Type, in3Type, in4Type, in5Type, in6Type, in7Type, in8Type, in9Type, in10Type, in11Type, in12Type, in13Type, outType }, //
			outType);
	}

	public static <I1, I2, I3, I4, I5, I6, I7, I8, I9, I10, I11, I12, I13, I14, O> Arity14<I1, I2, I3, I4, I5, I6, I7, I8, I9, I10, I11, I12, I13, I14, O> match(final OpService ops, final String opName,
		final Nil<I1> in1Type, final Nil<I2> in2Type, final Nil<I3> in3Type, final Nil<I4> in4Type, final Nil<I5> in5Type, final Nil<I6> in6Type, final Nil<I7> in7Type, final Nil<I8> in8Type, final Nil<I9> in9Type, final Nil<I10> in10Type, final Nil<I11> in11Type, final Nil<I12> in12Type, final Nil<I13> in13Type, final Nil<I14> in14Type, final Nil<O> outType)
	{
		final Nil<Arity14<I1, I2, I3, I4, I5, I6, I7, I8, I9, I10, I11, I12, I13, I14, O>> specialType =
			new Nil<Arity14<I1, I2, I3, I4, I5, I6, I7, I8, I9, I10, I11, I12, I13, I14, O>>()
		{
			@Override
			public Type getType() {
				return Types.parameterize(Arity14.class, //
					new Type[] { in1Type.getType(), in2Type.getType(), in3Type.getType(), in4Type.getType(), in5Type.getType(), in6Type.getType(), in7Type.getType(), in8Type.getType(), in9Type.getType(), in10Type.getType(), in11Type.getType(), in12Type.getType(), in13Type.getType(), in14Type.getType(), outType.getType() });
			}
		};
		return ops.findOp( //
			opName, //
			specialType, //
			new Nil<?>[] { in1Type, in2Type, in3Type, in4Type, in5Type, in6Type, in7Type, in8Type, in9Type, in10Type, in11Type, in12Type, in13Type, in14Type, outType }, //
			outType);
	}

	public static <I1, I2, I3, I4, I5, I6, I7, I8, I9, I10, I11, I12, I13, I14, I15, O> Arity15<I1, I2, I3, I4, I5, I6, I7, I8, I9, I10, I11, I12, I13, I14, I15, O> match(final OpService ops, final String opName,
		final Nil<I1> in1Type, final Nil<I2> in2Type, final Nil<I3> in3Type, final Nil<I4> in4Type, final Nil<I5> in5Type, final Nil<I6> in6Type, final Nil<I7> in7Type, final Nil<I8> in8Type, final Nil<I9> in9Type, final Nil<I10> in10Type, final Nil<I11> in11Type, final Nil<I12> in12Type, final Nil<I13> in13Type, final Nil<I14> in14Type, final Nil<I15> in15Type, final Nil<O> outType)
	{
		final Nil<Arity15<I1, I2, I3, I4, I5, I6, I7, I8, I9, I10, I11, I12, I13, I14, I15, O>> specialType =
			new Nil<Arity15<I1, I2, I3, I4, I5, I6, I7, I8, I9, I10, I11, I12, I13, I14, I15, O>>()
		{
			@Override
			public Type getType() {
				return Types.parameterize(Arity15.class, //
					new Type[] { in1Type.getType(), in2Type.getType(), in3Type.getType(), in4Type.getType(), in5Type.getType(), in6Type.getType(), in7Type.getType(), in8Type.getType(), in9Type.getType(), in10Type.getType(), in11Type.getType(), in12Type.getType(), in13Type.getType(), in14Type.getType(), in15Type.getType(), outType.getType() });
			}
		};
		return ops.findOp( //
			opName, //
			specialType, //
			new Nil<?>[] { in1Type, in2Type, in3Type, in4Type, in5Type, in6Type, in7Type, in8Type, in9Type, in10Type, in11Type, in12Type, in13Type, in14Type, in15Type, outType }, //
			outType);
	}

	public static <I1, I2, I3, I4, I5, I6, I7, I8, I9, I10, I11, I12, I13, I14, I15, I16, O> Arity16<I1, I2, I3, I4, I5, I6, I7, I8, I9, I10, I11, I12, I13, I14, I15, I16, O> match(final OpService ops, final String opName,
		final Nil<I1> in1Type, final Nil<I2> in2Type, final Nil<I3> in3Type, final Nil<I4> in4Type, final Nil<I5> in5Type, final Nil<I6> in6Type, final Nil<I7> in7Type, final Nil<I8> in8Type, final Nil<I9> in9Type, final Nil<I10> in10Type, final Nil<I11> in11Type, final Nil<I12> in12Type, final Nil<I13> in13Type, final Nil<I14> in14Type, final Nil<I15> in15Type, final Nil<I16> in16Type, final Nil<O> outType)
	{
		final Nil<Arity16<I1, I2, I3, I4, I5, I6, I7, I8, I9, I10, I11, I12, I13, I14, I15, I16, O>> specialType =
			new Nil<Arity16<I1, I2, I3, I4, I5, I6, I7, I8, I9, I10, I11, I12, I13, I14, I15, I16, O>>()
		{
			@Override
			public Type getType() {
				return Types.parameterize(Arity16.class, //
					new Type[] { in1Type.getType(), in2Type.getType(), in3Type.getType(), in4Type.getType(), in5Type.getType(), in6Type.getType(), in7Type.getType(), in8Type.getType(), in9Type.getType(), in10Type.getType(), in11Type.getType(), in12Type.getType(), in13Type.getType(), in14Type.getType(), in15Type.getType(), in16Type.getType(), outType.getType() });
			}
		};
		return ops.findOp( //
			opName, //
			specialType, //
			new Nil<?>[] { in1Type, in2Type, in3Type, in4Type, in5Type, in6Type, in7Type, in8Type, in9Type, in10Type, in11Type, in12Type, in13Type, in14Type, in15Type, in16Type, outType }, //
			outType);
	}

	// -- END TEMP --

	@FunctionalInterface
	public interface Arity0<O> extends Consumer<O> {
		void compute(@Mutable O out);

		@Override
		default void accept(final O out) {
			compute(out);
		}
	}

	@FunctionalInterface
	public interface Arity1<I, O> extends BiConsumer<I, O> {
		void compute(I in, @Mutable O out);

		@Override
		default void accept(final I in, final O out) {
			compute(in, out);
		}
	}

	@FunctionalInterface
	public interface Arity2<I1, I2, O> extends Consumers.Arity3<I1, I2, O> {
		void compute(I1 in1, I2 in2, @Mutable O out);

		@Override
		default void accept(final I1 in1, final I2 in2, final O out) {
			compute(in1, in2, out);
		}
	}

	@FunctionalInterface
	public interface Arity3<I1, I2, I3, O> extends Consumers.Arity4<I1, I2, I3, O> {
		void compute(I1 in1, I2 in2, I3 in3, @Mutable O out);

		@Override
		default void accept(final I1 in1, final I2 in2, final I3 in3, final O out) {
			compute(in1, in2, in3, out);
		}
	}

	@FunctionalInterface
	public interface Arity4<I1, I2, I3, I4, O> extends Consumers.Arity5<I1, I2, I3, I4, O> {
		void compute(I1 in1, I2 in2, I3 in3, I4 in4, @Mutable O out);

		@Override
		default void accept(final I1 in1, final I2 in2, final I3 in3, final I4 in4, final O out) {
			compute(in1, in2, in3, in4, out);
		}
	}

	@FunctionalInterface
	public interface Arity5<I1, I2, I3, I4, I5, O> extends Consumers.Arity6<I1, I2, I3, I4, I5, O> {
		void compute(I1 in1, I2 in2, I3 in3, I4 in4, I5 in5, @Mutable O out);

		@Override
		default void accept(final I1 in1, final I2 in2, final I3 in3, final I4 in4, final I5 in5, final O out) {
			compute(in1, in2, in3, in4, in5, out);
		}
	}

	@FunctionalInterface
	public interface Arity6<I1, I2, I3, I4, I5, I6, O> extends Consumers.Arity7<I1, I2, I3, I4, I5, I6, O> {
		void compute(I1 in1, I2 in2, I3 in3, I4 in4, I5 in5, I6 in6, @Mutable O out);

		@Override
		default void accept(final I1 in1, final I2 in2, final I3 in3, final I4 in4, final I5 in5, final I6 in6, final O out) {
			compute(in1, in2, in3, in4, in5, in6, out);
		}
	}

	@FunctionalInterface
	public interface Arity7<I1, I2, I3, I4, I5, I6, I7, O> extends Consumers.Arity8<I1, I2, I3, I4, I5, I6, I7, O> {
		void compute(I1 in1, I2 in2, I3 in3, I4 in4, I5 in5, I6 in6, I7 in7, @Mutable O out);

		@Override
		default void accept(final I1 in1, final I2 in2, final I3 in3, final I4 in4, final I5 in5, final I6 in6, final I7 in7, final O out) {
			compute(in1, in2, in3, in4, in5, in6, in7, out);
		}
	}

	@FunctionalInterface
	public interface Arity8<I1, I2, I3, I4, I5, I6, I7, I8, O> extends Consumers.Arity9<I1, I2, I3, I4, I5, I6, I7, I8, O> {
		void compute(I1 in1, I2 in2, I3 in3, I4 in4, I5 in5, I6 in6, I7 in7, I8 in8, @Mutable O out);

		@Override
		default void accept(final I1 in1, final I2 in2, final I3 in3, final I4 in4, final I5 in5, final I6 in6, final I7 in7, final I8 in8, final O out) {
			compute(in1, in2, in3, in4, in5, in6, in7, in8, out);
		}
	}

	@FunctionalInterface
	public interface Arity9<I1, I2, I3, I4, I5, I6, I7, I8, I9, O> extends Consumers.Arity10<I1, I2, I3, I4, I5, I6, I7, I8, I9, O> {
		void compute(I1 in1, I2 in2, I3 in3, I4 in4, I5 in5, I6 in6, I7 in7, I8 in8, I9 in9, @Mutable O out);

		@Override
		default void accept(final I1 in1, final I2 in2, final I3 in3, final I4 in4, final I5 in5, final I6 in6, final I7 in7, final I8 in8, final I9 in9, final O out) {
			compute(in1, in2, in3, in4, in5, in6, in7, in8, in9, out);
		}
	}

	@FunctionalInterface
	public interface Arity10<I1, I2, I3, I4, I5, I6, I7, I8, I9, I10, O> extends Consumers.Arity11<I1, I2, I3, I4, I5, I6, I7, I8, I9, I10, O> {
		void compute(I1 in1, I2 in2, I3 in3, I4 in4, I5 in5, I6 in6, I7 in7, I8 in8, I9 in9, I10 in10, @Mutable O out);

		@Override
		default void accept(final I1 in1, final I2 in2, final I3 in3, final I4 in4, final I5 in5, final I6 in6, final I7 in7, final I8 in8, final I9 in9, final I10 in10, final O out) {
			compute(in1, in2, in3, in4, in5, in6, in7, in8, in9, in10, out);
		}
	}

	@FunctionalInterface
	public interface Arity11<I1, I2, I3, I4, I5, I6, I7, I8, I9, I10, I11, O> extends Consumers.Arity12<I1, I2, I3, I4, I5, I6, I7, I8, I9, I10, I11, O> {
		void compute(I1 in1, I2 in2, I3 in3, I4 in4, I5 in5, I6 in6, I7 in7, I8 in8, I9 in9, I10 in10, I11 in11, @Mutable O out);

		@Override
		default void accept(final I1 in1, final I2 in2, final I3 in3, final I4 in4, final I5 in5, final I6 in6, final I7 in7, final I8 in8, final I9 in9, final I10 in10, final I11 in11, final O out) {
			compute(in1, in2, in3, in4, in5, in6, in7, in8, in9, in10, in11, out);
		}
	}

	@FunctionalInterface
	public interface Arity12<I1, I2, I3, I4, I5, I6, I7, I8, I9, I10, I11, I12, O> extends Consumers.Arity13<I1, I2, I3, I4, I5, I6, I7, I8, I9, I10, I11, I12, O> {
		void compute(I1 in1, I2 in2, I3 in3, I4 in4, I5 in5, I6 in6, I7 in7, I8 in8, I9 in9, I10 in10, I11 in11, I12 in12, @Mutable O out);

		@Override
		default void accept(final I1 in1, final I2 in2, final I3 in3, final I4 in4, final I5 in5, final I6 in6, final I7 in7, final I8 in8, final I9 in9, final I10 in10, final I11 in11, final I12 in12, final O out) {
			compute(in1, in2, in3, in4, in5, in6, in7, in8, in9, in10, in11, in12, out);
		}
	}

	@FunctionalInterface
	public interface Arity13<I1, I2, I3, I4, I5, I6, I7, I8, I9, I10, I11, I12, I13, O> extends Consumers.Arity14<I1, I2, I3, I4, I5, I6, I7, I8, I9, I10, I11, I12, I13, O> {
		void compute(I1 in1, I2 in2, I3 in3, I4 in4, I5 in5, I6 in6, I7 in7, I8 in8, I9 in9, I10 in10, I11 in11, I12 in12, I13 in13, @Mutable O out);

		@Override
		default void accept(final I1 in1, final I2 in2, final I3 in3, final I4 in4, final I5 in5, final I6 in6, final I7 in7, final I8 in8, final I9 in9, final I10 in10, final I11 in11, final I12 in12, final I13 in13, final O out) {
			compute(in1, in2, in3, in4, in5, in6, in7, in8, in9, in10, in11, in12, in13, out);
		}
	}

	@FunctionalInterface
	public interface Arity14<I1, I2, I3, I4, I5, I6, I7, I8, I9, I10, I11, I12, I13, I14, O> extends Consumers.Arity15<I1, I2, I3, I4, I5, I6, I7, I8, I9, I10, I11, I12, I13, I14, O> {
		void compute(I1 in1, I2 in2, I3 in3, I4 in4, I5 in5, I6 in6, I7 in7, I8 in8, I9 in9, I10 in10, I11 in11, I12 in12, I13 in13, I14 in14, @Mutable O out);

		@Override
		default void accept(final I1 in1, final I2 in2, final I3 in3, final I4 in4, final I5 in5, final I6 in6, final I7 in7, final I8 in8, final I9 in9, final I10 in10, final I11 in11, final I12 in12, final I13 in13, final I14 in14, final O out) {
			compute(in1, in2, in3, in4, in5, in6, in7, in8, in9, in10, in11, in12, in13, in14, out);
		}
	}

	@FunctionalInterface
	public interface Arity15<I1, I2, I3, I4, I5, I6, I7, I8, I9, I10, I11, I12, I13, I14, I15, O> extends Consumers.Arity16<I1, I2, I3, I4, I5, I6, I7, I8, I9, I10, I11, I12, I13, I14, I15, O> {
		void compute(I1 in1, I2 in2, I3 in3, I4 in4, I5 in5, I6 in6, I7 in7, I8 in8, I9 in9, I10 in10, I11 in11, I12 in12, I13 in13, I14 in14, I15 in15, @Mutable O out);

		@Override
		default void accept(final I1 in1, final I2 in2, final I3 in3, final I4 in4, final I5 in5, final I6 in6, final I7 in7, final I8 in8, final I9 in9, final I10 in10, final I11 in11, final I12 in12, final I13 in13, final I14 in14, final I15 in15, final O out) {
			compute(in1, in2, in3, in4, in5, in6, in7, in8, in9, in10, in11, in12, in13, in14, in15, out);
		}
	}

	@FunctionalInterface
	public interface Arity16<I1, I2, I3, I4, I5, I6, I7, I8, I9, I10, I11, I12, I13, I14, I15, I16, O> extends Consumers.Arity17<I1, I2, I3, I4, I5, I6, I7, I8, I9, I10, I11, I12, I13, I14, I15, I16, O> {
		void compute(I1 in1, I2 in2, I3 in3, I4 in4, I5 in5, I6 in6, I7 in7, I8 in8, I9 in9, I10 in10, I11 in11, I12 in12, I13 in13, I14 in14, I15 in15, I16 in16, @Mutable O out);

		@Override
		default void accept(final I1 in1, final I2 in2, final I3 in3, final I4 in4, final I5 in5, final I6 in6, final I7 in7, final I8 in8, final I9 in9, final I10 in10, final I11 in11, final I12 in12, final I13 in13, final I14 in14, final I15 in15, final I16 in16, final O out) {
			compute(in1, in2, in3, in4, in5, in6, in7, in8, in9, in10, in11, in12, in13, in14, in15, in16, out);
		}
	}
}
