# Use this file to construct an environment for
# working with SciJava Ops in a runtime setting.

# First, install mambaforge:
#
#   https://github.com/conda-forge/miniforge#mambaforge
#
# Then run:
#
#   mamba env create
#   mamba activate scijava-ops
#
# It includes the dependencies needed for using SciJava Ops, but not tools
# for developer-related actions like running automated tests (pytest),
# linting the code (black), and generating the API documentation (sphinx).

name: scijava-ops
channels:
  - conda-forge
  - defaults
dependencies:
  - python >= 3.7
  # Project dependencies
  - jupyter
  - openjdk >= 17
  - scyjava
  # Project from source
  - pip
