name: scijava-docs
channels:
  - conda-forge
dependencies:
  - python==3.11
  - myst-nb==1.3.0
  - openjdk=11
  - plotly
  - sphinx==8.2.2
  - sphinx-copybutton==0.5.2
  - sphinx_rtd_theme==3.0.2

  - pip
  - pip:
      # NB: Needed for newer sphinx versions - see
      # https://github.com/thclark/sphinx-charts/issues/23
      - sphinxcontrib-jquery 
      - sphinx-multiproject==1.0.0
      - readthedocs-sphinx-search==0.3.2
      - sphinx-tabs==3.4.7
      - sphinx_charts==0.2.1